In [13]:
import numpy as np
X=np.array(([2,9],[1,5],[3,6]),dtype=float)
y=np.array(([92],[86],[89]),dtype=float)
y=y/100
def sigmoid(X):
    return 1/(1+np.exp(-X))
def derivatives_sigmoid(X):
    return X*(1-X)
epoch=2
ir=0.1
inputlayer_neurons=2
hiddenlayer_neurons=3
output_neurons=1
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))
for i in range(epoch):
    hinp1=np.dot(X,wh)
    hinp=hinp1+bh
    hlayer_act=sigmoid(hinp)
    outinp1=np.dot(hlayer_act,wout)
    outinp=outinp1+bout
    output=sigmoid(outinp)
    EO=y-output
    outgrad=derivatives_sigmoid(output)
    d_output=EO*outgrad
    EH=d_output.dot(wout.T)
    hiddengrad=derivatives_sigmoid(hlayer_act)
    d_hiddenlayer=EH*hiddengrad
    wout+=hlayer_act.T.dot(d_output)*ir
    wh+=X.T.dot(d_hiddenlayer)*ir
    print("-----EPOCH--",i+1,"starts--")
    print("input:\n",str(X))
    print("actual output:\n",str(y))
    print("predicted output:\n",output)
    print("EPOCH_",i+1,"ends---")
print("input:\n",str(X))
print("actual output:\n",str(y))
print("predicted output:\n",output)

-----EPOCH-- 1 starts--
input:
 [[2. 9.]
 [1. 5.]
 [3. 6.]]
actual output:
 [[0.92]
 [0.86]
 [0.89]]
predicted output:
 [[0.86747848]
 [0.85730533]
 [0.86479586]]
EPOCH_ 1 ends---
-----EPOCH-- 2 starts--
input:
 [[2. 9.]
 [1. 5.]
 [3. 6.]]
actual output:
 [[0.92]
 [0.86]
 [0.89]]
predicted output:
 [[0.86779079]
 [0.85762363]
 [0.86510869]]
EPOCH_ 2 ends---
input:
 [[2. 9.]
 [1. 5.]
 [3. 6.]]
actual output:
 [[0.92]
 [0.86]
 [0.89]]
predicted output:
 [[0.86779079]
 [0.85762363]
 [0.86510869]]
